[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
evm_version = 'shanghai'
viaIR = true
fs_permissions = [{ access = "read", path = "test/json/json_bible/" }]

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
